[package]
name = "react-rust-app"
version = "0.1.0"
authors = ["Andrew Steinheiser <me@iamandrew.io>"]

[lib]
name = "random_number"
crate-type = ["cdylib"]

[dependencies]
rand = "0.6.1"
wasm-bindgen = "0.2"
